name: Python Trending Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir çalıştır
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  post-trending:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Not: Burada GH_PAT kullanıyoruz, çünkü GITHUB_TOKEN zaten özel bir değişken
      run: python bot.py