name: Python Trending Bot (Manual Only)

on:
  workflow_dispatch:  # Sadece manuel tetikleme ile çalışacak
  # schedule satırı kaldırıldı

jobs:
  post-trending:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: python bot.py
      timeout-minutes: 5
